require('dotenv').config();
console.log('Million Accelerator Bot started');

const { startTokenMonitor } = require('./tokenMonitor');
const { startHalvingMonitor } = require('./strategies/halvingDetector');
const { startStakingTracker } = require('./strategies/stakingTracker');
const { startTokenScoringEngine } = require('./strategies/tokenScoringEngine');
const { startDexActivityWatcher } = require('./strategies/dexActivityWatcher');
const { startNewsShockResponse } = require('./strategies/newsShockResponse');
const { startPumpReloadWatcher } = require('./strategies/pumpReloadStrategy');
const { startSentimentHypeScanner } = require('./strategies/sentimentHypeScanner');
const { startPortfolioHeatmap } = require('./strategies/portfolioHeatmap');
const { startAutoRebalance } = require('./strategies/autoRebalance');
const { startProfitTracker } = require('./strategies/profitTracker');
const { startCapitalAllocator } = require('./strategies/capitalAllocator');
const { startRiskAlerts } = require('./strategies/riskAlerts');

startTokenMonitor();
startHalvingMonitor();
startStakingTracker();
startTokenScoringEngine();
startDexActivityWatcher();
startNewsShockResponse();
startPumpReloadWatcher();
startSentimentHypeScanner();
startPortfolioHeatmap();
startAutoRebalance();
startProfitTracker();
startCapitalAllocator();
startRiskAlerts();
